import 'helpers.dart';

String appText(AppLang lang, String key) {
  final Map<String, Map<String, String>> data = {
    'university_app': {
      'FA': 'اپلیکیشن ارتباط با دانشگاه',
      'EN': 'University Communication App',
      'AR': 'تطبيق التواصل مع الجامعة',
    },
    'university_subtitle': {
      'FA': 'ارتباط ساده‌تر دانشجویان بین‌الملل با واحدهای دانشگاه',
      'EN': 'A simpler connection between international students and university units',
      'AR': 'تواصل أسهل بين الطلاب الدوليين ووحدات الجامعة',
    },
    'units': {'FA': 'واحدها', 'EN': 'Units', 'AR': 'الوحدات'},
    'support': {'FA': 'پشتیبانی', 'EN': 'Support', 'AR': 'الدعم'},
    'international': {'FA': 'امور بین‌الملل', 'EN': 'International Affairs', 'AR': 'الشؤون الدولية'},
    'student_services': {'FA': 'خدمات دانشجویی', 'EN': 'Student Services', 'AR': 'خدمات الطلاب'},
    'education': {'FA': 'آموزش', 'EN': 'Education', 'AR': 'التعليم'},
    'consular': {'FA': 'کنسولی', 'EN': 'Consular', 'AR': 'القنصلية'},
    'other_services': {'FA': 'سایر خدمات', 'EN': 'Other Services', 'AR': 'خدمات أخرى'},
    'enter_section': {'FA': 'ورود به بخش', 'EN': 'Enter', 'AR': 'الدخول إلى قسم'},
    'profile': {'FA': 'پروفایل', 'EN': 'Profile', 'AR': 'الملف الشخصي'},
    'notifications': {'FA': 'اعلان‌ها', 'EN': 'Notifications', 'AR': 'الإشعارات'},
    'unread': {'FA': 'اعلان نخوانده', 'EN': 'Unread notifications', 'AR': 'إشعارات غير مقروءة'},
    'taxi': {'FA': 'تاکسی دانشگاه', 'EN': 'University Taxi', 'AR': 'تاكسي الجامعة'},
    'translation': {'FA': 'خدمات ترجمه', 'EN': 'Translation Services', 'AR': 'خدمات الترجمة'},
    'insurance': {'FA': 'بیمه دانشجویی', 'EN': 'Student Insurance', 'AR': 'تأمين الطلاب'},
    'bank': {'FA': 'خدمات بانکی', 'EN': 'Banking Services', 'AR': 'الخدمات المصرفية'},
    'restaurant': {'FA': 'رستوران دانشگاه', 'EN': 'University Restaurant', 'AR': 'مطعم الجامعة'},
    'gym': {'FA': 'سالن ورزشی', 'EN': 'Gym', 'AR': 'صالة الألعاب الرياضية'},
    'library': {'FA': 'کتابخانه', 'EN': 'Library', 'AR': 'المكتبة'},
    'printing': {'FA': 'چاپ و تکثیر', 'EN': 'Printing Services', 'AR': 'خدمات الطباعة'},
    'my_conversations': {'FA': 'گفتگوهای من', 'EN': 'My Conversations', 'AR': 'محادثاتي'},
    'search_conversations': {'FA': 'جستجو در گفتگوها...', 'EN': 'Search conversations...', 'AR': 'البحث في المحادثات...'},
    'new_conversation': {'FA': 'گفتگوی جدید', 'EN': 'New Conversation', 'AR': 'محادثة جديدة'},
    'tracking': {'FA': 'پیگیری', 'EN': 'Tracking', 'AR': 'متابعة'},
    'quick_access': {'FA': 'دسترسی سریع', 'EN': 'Quick Access', 'AR': 'وصول سريع'},
    'common_items': {'FA': 'موارد پرکاربرد', 'EN': 'Common Items', 'AR': 'العناصر الشائعة'},
    'unit_info': {'FA': 'اطلاعات واحد', 'EN': 'Unit Information', 'AR': 'معلومات الوحدة'},
    'response_hours': {'FA': 'ساعت پاسخگویی: 8 الی 16', 'EN': 'Response hours: 8 to 16', 'AR': 'ساعات الرد: 8 إلى 16'},
    'contact_unit': {'FA': 'تماس با واحد', 'EN': 'Contact Unit', 'AR': 'الاتصال بالوحدة'},
    'write_message': {'FA': 'پیام خود را بنویسید...', 'EN': 'Write your message...', 'AR': 'اكتب رسالتك...'},
    'message_received': {'FA': 'پیام شما دریافت شد و توسط کارشناس بررسی می‌شود.', 'EN': 'Your message has been received and will be reviewed by the staff.', 'AR': 'تم استلام رسالتك وسيتم فحصها من قبل الموظف المختص.'},
    'welcome_message': {'FA': 'سلام 👋\nبه این بخش خوش آمدید. لطفاً درخواست خود را کامل توضیح دهید.', 'EN': 'Hello!\nWelcome to this section. Please describe your request completely.', 'AR': 'مرحباً!\nأهلاً بك في هذا القسم. يرجى شرح طلبك بشكل كامل.'},
    'sample_user_message': {'FA': 'سلام، من یک درخواست اداری دارم. لطفاً راهنمایی کنید چه مدارکی لازم است.', 'EN': 'Hello, I have an administrative request. Please tell me what documents are required.', 'AR': 'مرحباً، لدي طلب إداري. يرجى إرشادي إلى المستندات المطلوبة.'},
    'sample_staff_message': {'FA': 'برای ثبت درخواست، لطفاً نوع درخواست را مشخص کنید و مدارک مرتبط را ارسال نمایید.', 'EN': 'To register the request, please specify the request type and send the related documents.', 'AR': 'لتسجيل الطلب، يرجى تحديد نوع الطلب وإرسال المستندات ذات الصلة.'},
    'request_about': {'FA': 'درخواست درباره', 'EN': 'Request about', 'AR': 'طلب حول'},
    'request_registered': {'FA': 'درخواست شما ثبت شد. لطفاً جزئیات بیشتری ارسال کنید.', 'EN': 'Your request has been registered. Please send more details.', 'AR': 'تم تسجيل طلبك. يرجى إرسال المزيد من التفاصيل.'},
    'support_chat_welcome': {'FA': 'سلام! من دستیار پشتیبانی دانشگاه هستم. چطور می‌تونم کمکتون کنم؟', 'EN': 'Hello! I am the university support assistant. How can I help you?', 'AR': 'مرحباً! أنا مساعد الدعم بالجامعة. كيف يمكنني مساعدتك؟'},
    'support_chat_certificate_response': {'FA': 'برای دریافت گواهی اشتغال به تحصیل، لطفاً به بخش آموزش مراجعه کنید.', 'EN': 'To get a student certificate, please visit the Education section.', 'AR': 'للحصول على شهادة قيد دراسي، يرجى زيارة قسم التعليم.'},
    'support_chat_dormitory_response': {'FA': 'درخواست خوابگاه از طریق بخش خدمات دانشجویی انجام می‌شود.', 'EN': 'Dormitory requests are made through the Student Services section.', 'AR': 'Dormitory requests are made through the Student Services section.'},
    'support_chat_visa_response': {'FA': 'برای تمدید یا صدور ویزا، لطفاً با بخش کنسولی ارتباط بگیرید.', 'EN': 'To extend or issue a visa, please contact the Consular section.', 'AR': 'لتمديد أو إصدار تأشيرة، يرجى التواصل مع القسم القنصلي.'},
    'support_chat_grade_response': {'FA': 'برای دریافت ریز نمرات، از بخش آموزش درخواست دهید.', 'EN': 'To get your transcript, request it from the Education section.', 'AR': 'للحصول على كشف درجاتك، اطلبه من قسم التعليم.'},
    'support_chat_greeting_response': {'FA': 'سلام! خوشحالم که با شما صحبت می‌کنم.', 'EN': 'Hello! Nice to talk to you.', 'AR': 'مرحباً! يسعدني التحدث إليك.'},
    'support_chat_thanks_response': {'FA': 'خواهش می‌کنم! هر وقت سوالی داشتید در خدمتم.', 'EN': 'You\'re welcome! I\'m here whenever you have a question.', 'AR': 'عفواً! أنا هنا كلما كان لديك سؤال.'},
    'support_chat_unclear_response': {'FA': 'متوجه نشدم. لطفاً سوال خود را واضح‌تر بپرسید.', 'EN': 'I didn\'t understand. Please ask your question more clearly.', 'AR': 'لم أفهم. يرجى طرح سؤالك بشكل أوضح.'},
  };
  return data[key]?[_langKey(lang)] ?? key;
}
